### PR TITLE
Adding a Landsat Scene Synthesis Raster Function

### PR DESCRIPTION
**Pull request by gbrunner**
@jdrisdelle I'm contributing a python raster function and RTF that show how you can perform analysis on a stack of landsat scenes over time and generate an *average* monthly image from that stack of landsat scenes. I wrote it for Landsat 5, but it can be applied for other sensors.

### CODE REVIEW

**Comment by jdrisdelle** [comment]
Awesome. Thanks for contributing @gbrunner .  Are you updating the chuckClose.py  script as well? Also can you remove the reference to your local machine in the rft. For now you can just use the name of the python file in there. Pro doesn't really play with relative paths very well so that rft won't really work (but none of them really do).  I am debating using the well know home folder paths in all the rfts but that will require users to download the repo to the well known home folder for 10.x and Pro in order for them to work.

**Comment by gbrunner** [comment]
@jdrisdelle I have removed the path from the RFT file. I meant to catch that before I committed.I am also submitting the update to ChuckClose.py.

**Comment by gbrunner** [comment]
Bam. @jdrisdelle i resolved the conflict on this repo. I'm hoping to start committing some more stuff to this over the next few months.

**Comment by jdrisdelle** [comment]
Looks good.

**Pull request merged**
