### PR TITLE
Feature/linear spectral unmixing

### PR DESCRIPTION
**Pull request by jwasil**
@jdrisdelle @akferoz please take a look.  My fork includes the latest commits from this repo's master, but really the only true contribution from my end should be the addition of functions/LinearSpectralUnmixing.py.  If we need to revisit how things were handled on my fork before we accept this PR, please let me know.  Thanks!

### CODE REVIEW

**Comment by akferoz** [comment]
@jdrisdelle, @jwasil: PR merged with LinearUnmixing branch (off master, here: https://github.com/Esri/raster-functions/tree/LinearUnmixing). 

I'll merge changes to master after the few remaining issues with ArcGIS 10.3.1 and Pro are resolved. @jwasil, you can continue making changes (if needed) on your fork as well. I'll pull at least once more before merging with master.

**Comment by jwasil** [comment]
@akferoz this sounds good, thanks.

What do you think about the default value for input param 2, at https://github.com/Esri/raster-functions/blob/LinearUnmixing/functions/LinearSpectralUnmixing.py#L25 ?

This default value was convenient for me when testing endmember signature means for my specific Landsat testing scene, but I was thinking that it should be clear to the end-user that the input here needs to be changed.  However, it also serves to show how it should be formatted going in.  There are also some limitations on the total number of endmembers that can be supplied to the function.  Just trying to brainstorm on ways to convey this info clearly.

**Comment by jwasil** [comment]
:+1:

**Comment by scw** [comment]
Thanks @jwasil!

**Comment by jwasil** [comment]
My pleasure, @scw! If you end up using it and have any ?'s, feel free to let me know.

**Pull request merged**
